### ISSUE TITLE
run this project error

### ISSUE THREAD

**Issue by zgq1987** [Nike-Inc/riposte-microservice-template#10]
1) No implementation for java.lang.Boolean annotated with @com.google.inject.name.Named(value=disableCassandra) was bound.
  while locating java.lang.Boolean annotated with @com.google.inject.name.Named(value=disableCassandra)
    for parameter 0 at com.myorg.ripostemicroservicetemplate.endpoints.ExampleCassandraAsyncEndpoint.<init>(ExampleCassandraAsyncEndpoint.java:58)
  at com.myorg.ripostemicroservicetemplate.server.config.guice.AppGuiceModule.appEndpoints(AppGuiceModule.java:100)

**Comment by nicmunroe** [comment]
You'll get this error if you don't specify the correct `@appId` and `@environment` System Properties when starting up the server. See this documentation for details: https://github.com/Nike-Inc/riposte-microservice-template#running_the_server.

You should be able to successfully run the server using `./gradlew run` or `./debugShadowJar.sh` as those mechanisms are already setup to start the server with the correct `@appId` and `@environment` System Properties. If you want to launch the server any other way (i.e. from your IDE directly) then please read the linked documentation on running the server carefully so you understand what those System Properties are for and how they relate to your `*.conf` files.
